pubsub_redis:
    class: 'AnyEvent::Redis::RipeRedis'
    args:
        host: 'localhost'
        port: 6379
        encoding: 'utf8'
        reconnect: 20
        connection_timeout: 5

subscriptions_service:
    class: 'ClubChat::MessagesPupSub::SubscriptionsService'
    args:
        redis_handler: {ref: pubsub_redis}
        channel: 'club_chat_ps'
authentication_service:
    class: 'ClubChat::Authentication::AuthenticationServiceDummy'
messages_handler:
    class: 'ClubChat::MessagesHandler'
    args:
        authentication_service: {ref:authentication_service}
        message_registrator: {ref:message_registrator}