subscribe_redis:
    class: 'ClubChat::RedisConnection::AnyEventRedis'
    method: getConnection
    args:
        - '127.0.0.1'

publicate_redis:
    class: 'ClubChat::RedisConnection::AnyEventRedis'
    args:
        address: '127.0.0.1'

subscriptions_service:
    class: 'ClubChat::MessagesPupSub::SubscriptionsService'
    args:
        redis_subscription_handler: {ref: subscribe_redis}
        redis_publishing_handler: {ref: publicate_redis}
        channel: 'club_chat_ps'
authentication_service:
    class: 'ClubChat::Authentication::AuthenticationServiceDummy'
messages_handler:
    class: 'ClubChat::MessagesHandler'
    args:
        authentication_service: {ref: authentication_service}
        message_registrator: {ref: subscriptions_service}
